### ISSUE TITLE
void ace_common::PrintStrBase::flush()' marked 'override', but does not override

### ISSUE THREAD

**Issue by gcanzalo** [bxparks/AceCommon#24]
Hi:

How do I fix:

PrintStr.h:127:10: error: 'void ace_common::PrintStrBase::flush()' marked 'override', but does not override
     void flush() override {
          ^

exit status 1

Compilation error: exit status 1

Thank you!

**Comment by bxparks** [comment]
What platform are you compiling this under?
And did you notice the long comment that I wrote on that function?
https://github.com/bxparks/AceCommon/blob/develop/src/print_str/PrintStr.h#L89

**Comment by gcanzalo** [comment]
Hi:

It's a HiLetgo ESP-WROOM-32 ESP32 ESP-32S. If I'm understanding your comment, it should work?

**Comment by bxparks** [comment]
If you are using the latest ESP32 Core, then it should. What is your tool chain and board version?

**Comment by gcanzalo** [comment]
Arduino IDE
Version: 2.0.3
Date: 2022-12-05T09:30:25.331Z
CLI Version: 0.29.0 [76251df9]

Board v1.1

**Comment by bxparks** [comment]
There is no ESP32 board v1.1. The latest one is 2.0.7. Try that instead.

**Comment by bxparks** [comment]
If there are no further updates, I'm closing this.
